-- Supabase/Postgres schema for Hub e-commerce & ERP integration
-- This schema merges the MySQL and SQLite definitions and includes backend tables
-- that the app still queries during setup and runtime.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text UNIQUE NOT NULL,
    password_hash text NOT NULL,
    first_name text,
    middle_name text,
    last_name text,
    suffix text,
    phone text,
    avatar_url text,
    gender text,
    birthdate text,
    address_line1 text,
    address_line2 text,
    city text,
    province text,
    region text,
    postal_code text,
    role text NOT NULL DEFAULT 'customer' CHECK (role IN ('admin', 'customer', 'seller', 'rider')),
    otp_code text,
    is_verified boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sellers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    business_name text,
    category text,
    business_permit text,
    valid_id text,
    address_proof text,
    business_logo text,
    region text,
    province text,
    city text,
    verified boolean NOT NULL DEFAULT false,
    missing_requirements text,
    shop_status text NOT NULL DEFAULT 'pending' CHECK (shop_status IN ('pending', 'active', 'suspended')),
    approved_at timestamptz,
    declined_at timestamptz,
    declined_by bigint REFERENCES users(id) ON DELETE SET NULL,
    decline_reason text,
    store_name text,
    store_description text,
    store_logo text,
    store_banner text,
    support_phone text,
    support_email text,
    tax_id text,
    payout_method text,
    bank_account_name text,
    bank_account_number text
);

CREATE TABLE IF NOT EXISTS riders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    vehicle_type text,
    driver_license text,
    valid_id text,
    vehicle_or_cr text,
    profile_photo text,
    plate_number text,
    verified boolean NOT NULL DEFAULT false,
    rider_status text NOT NULL DEFAULT 'pending' CHECK (rider_status IN ('pending', 'active', 'suspended', 'offline')),
    availability text NOT NULL DEFAULT 'offline' CHECK (availability IN ('available', 'busy', 'offline')),
    current_location text,
    approved_at timestamptz,
    last_active timestamptz,
    suspended_at timestamptz,
    suspended_by bigint REFERENCES users(id) ON DELETE SET NULL,
    suspension_reason text,
    suspension_type text CHECK (suspension_type IN ('temporary', 'permanent')),
    missing_requirements text,
    declined_at timestamptz,
    declined_by bigint REFERENCES users(id) ON DELETE SET NULL,
    decline_reason text,
    phone text,
    avatar_url text,
    address_line1 text,
    city text,
    province text,
    region text,
    status text,
    license_expiry text
);

CREATE TABLE IF NOT EXISTS suppliers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    contact text
);

CREATE TABLE IF NOT EXISTS products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    description text,
    price numeric(12,2) NOT NULL,
    stock integer NOT NULL DEFAULT 0,
    seller_id bigint REFERENCES users(id) ON DELETE SET NULL,
    store_id bigint,
    category text,
    img_url text,
    manufacture_date date,
    expiry_date date,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS product_variation_options (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    variation_type text NOT NULL,
    variation_value text NOT NULL,
    price_adjustment numeric(12,2) NOT NULL DEFAULT 0,
    stock integer NOT NULL DEFAULT 0,
    sku text UNIQUE,
    is_available boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_product_variation ON product_variation_options(product_id, variation_type);
CREATE INDEX IF NOT EXISTS idx_sku ON product_variation_options(sku);

CREATE TABLE IF NOT EXISTS inventory_movements_variations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variation_id bigint NOT NULL REFERENCES product_variation_options(id) ON DELETE CASCADE,
    qty integer NOT NULL,
    movement_type text NOT NULL CHECK (movement_type IN ('sale', 'purchase', 'adjustment', 'restock')),
    ref text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS inventory_movements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    qty integer NOT NULL,
    movement_type text NOT NULL CHECK (movement_type IN ('sale', 'purchase', 'adjustment')),
    ref text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint REFERENCES users(id) ON DELETE SET NULL,
    customer_name text,
    customer_phone text,
    customer_address text,
    subtotal numeric(12,2),
    delivery_fee numeric(12,2),
    total numeric(12,2),
    payment text,
    status text NOT NULL DEFAULT 'placed' CHECK (status IN ('placed','pending','processing','ready','dispatched','in-transit','shipped','delivered','completed','cancelled')),
    rider_id bigint REFERENCES riders(id) ON DELETE SET NULL,
    cancellation_reason text,
    created_at timestamptz NOT NULL DEFAULT now(),
    delivered_at timestamptz
);

CREATE TABLE IF NOT EXISTS order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id bigint REFERENCES products(id),
    variation_id bigint REFERENCES product_variation_options(id) ON DELETE SET NULL,
    variation_details text,
    quantity integer NOT NULL DEFAULT 1,
    price numeric(12,2)
);

CREATE TABLE IF NOT EXISTS purchase_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id bigint REFERENCES suppliers(id),
    status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'ordered', 'received', 'closed')),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS purchase_order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_id bigint NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
    product_id bigint REFERENCES products(id),
    quantity integer NOT NULL DEFAULT 1,
    price numeric(12,2)
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash text NOT NULL,
    expires_at timestamptz NOT NULL,
    revoked boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS wishlist (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    product_id bigint NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    quantity integer NOT NULL DEFAULT 1,
    price_total numeric(12,2),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, product_id)
);

CREATE INDEX IF NOT EXISTS idx_user_wishlist ON wishlist(user_id);

CREATE TABLE IF NOT EXISTS cart_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    product_id bigint NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    variation_id bigint REFERENCES product_variation_options(id) ON DELETE CASCADE,
    quantity integer NOT NULL DEFAULT 1,
    price_total numeric(12,2),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, product_id, variation_id)
);

CREATE INDEX IF NOT EXISTS idx_user_cart ON cart_items(user_id);

CREATE TABLE IF NOT EXISTS conversations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    seller_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    store_id bigint,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (customer_id, seller_id)
);

CREATE INDEX IF NOT EXISTS idx_customer_conversation ON conversations(customer_id);
CREATE INDEX IF NOT EXISTS idx_seller_conversation ON conversations(seller_id);

CREATE TABLE IF NOT EXISTS messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id bigint NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    sender_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    sender_type text NOT NULL CHECK (sender_type IN ('customer', 'seller')),
    message text NOT NULL,
    is_read boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_message_conversation ON messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_message_sender ON messages(sender_id);
CREATE INDEX IF NOT EXISTS idx_message_created ON messages(created_at);

CREATE TABLE IF NOT EXISTS audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type text NOT NULL CHECK (target_type IN ('seller', 'rider', 'product', 'order', 'user')),
    target_id bigint NOT NULL,
    action_type text NOT NULL CHECK (action_type IN ('warning', 'fine', 'restriction', 'ban', 'unban', 'suspend', 'unsuspend', 'refund', 'delete', 'approve')),
    reason text,
    amount numeric(12,2),
    duration_days integer,
    admin_id bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_target ON audit_logs(target_type, target_id);
CREATE INDEX IF NOT EXISTS idx_action ON audit_logs(action_type);
CREATE INDEX IF NOT EXISTS idx_created_audit ON audit_logs(created_at);

CREATE TABLE IF NOT EXISTS notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type text NOT NULL DEFAULT 'general',
    title text NOT NULL,
    body text,
    message text,
    action_url text,
    "read" boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_read ON notifications(user_id, "read");

CREATE TABLE IF NOT EXISTS verification_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    user_type text NOT NULL CHECK (user_type IN ('seller', 'rider')),
    document_type text NOT NULL,
    file_path text NOT NULL,
    file_name text NOT NULL,
    uploaded_at timestamptz NOT NULL DEFAULT now(),
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    admin_notes text
);

CREATE INDEX IF NOT EXISTS idx_user_type ON verification_documents(user_id, user_type);
CREATE INDEX IF NOT EXISTS idx_verification_status ON verification_documents(status);

CREATE TABLE IF NOT EXISTS otp_codes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text,
    code text NOT NULL,
    expires_at timestamptz NOT NULL,
    used boolean NOT NULL DEFAULT false,
    attempts integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    rating integer CHECK (rating BETWEEN 1 AND 5),
    title text,
    body text,
    comment text,
    images text,
    customer_id bigint,
    order_id bigint,
    seller_id bigint,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS customer_reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    order_id bigint,
    product_id bigint,
    seller_id bigint,
    rating integer CHECK (rating BETWEEN 1 AND 5),
    comment text,
    images text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS rider_reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rider_id bigint REFERENCES riders(id) ON DELETE SET NULL,
    customer_id bigint REFERENCES users(id) ON DELETE SET NULL,
    order_id bigint,
    rating integer CHECK (rating BETWEEN 1 AND 5),
    comment text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS rider_locations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rider_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    order_id bigint REFERENCES orders(id) ON DELETE SET NULL,
    latitude numeric(10,7),
    longitude numeric(10,7),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS proof_of_delivery (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    rider_id bigint REFERENCES users(id) ON DELETE SET NULL,
    image_url text,
    signature_url text,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS disputes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    complainant_id bigint REFERENCES users(id),
    complainant_role text,
    description text,
    status text NOT NULL DEFAULT 'open',
    resolution text,
    created_at timestamptz NOT NULL DEFAULT now(),
    resolved_at timestamptz
);

CREATE TABLE IF NOT EXISTS rider_earnings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rider_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    order_id bigint REFERENCES orders(id) ON DELETE SET NULL,
    amount numeric(12,2),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS rider_payouts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rider_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    amount numeric(12,2),
    status text NOT NULL DEFAULT 'pending',
    payment_method text,
    payout_date timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS return_refund_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    customer_id bigint REFERENCES users(id) ON DELETE SET NULL,
    seller_id bigint REFERENCES users(id) ON DELETE SET NULL,
    product_id bigint REFERENCES products(id) ON DELETE SET NULL,
    reason text,
    status text NOT NULL DEFAULT 'pending',
    seller_response text NOT NULL DEFAULT 'pending' CHECK (seller_response IN ('pending', 'approved', 'rejected', 'request_info')),
    rejection_reason text,
    pickup_rider_id bigint REFERENCES riders(id) ON DELETE SET NULL,
    pickup_scheduled_at timestamptz,
    pickup_completed_at timestamptz,
    item_received_at timestamptz,
    refund_processed_at timestamptz,
    evidence_images text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_return_refund_order ON return_refund_requests(order_id);
CREATE INDEX IF NOT EXISTS idx_return_refund_customer ON return_refund_requests(customer_id);
CREATE INDEX IF NOT EXISTS idx_return_refund_seller ON return_refund_requests(seller_id);
CREATE INDEX IF NOT EXISTS idx_return_refund_status ON return_refund_requests(status);
