-- Add seller/rider review workflow columns and audit logs.

ALTER TABLE public.sellers
    ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'active', 'declined')),
    ADD COLUMN IF NOT EXISTS rejection_reason text,
    ADD COLUMN IF NOT EXISTS reviewed_by bigint REFERENCES public.users(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS reviewed_at timestamptz,
    ADD COLUMN IF NOT EXISTS contact_number text,
    ADD COLUMN IF NOT EXISTS document_url text;

ALTER TABLE public.riders
    ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'active', 'declined', 'suspended')),
    ADD COLUMN IF NOT EXISTS rejection_reason text,
    ADD COLUMN IF NOT EXISTS reviewed_by bigint REFERENCES public.users(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS reviewed_at timestamptz,
    ADD COLUMN IF NOT EXISTS contact_number text,
    ADD COLUMN IF NOT EXISTS document_url text;

CREATE TABLE IF NOT EXISTS public.seller_audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id bigint NOT NULL REFERENCES public.sellers(id) ON DELETE CASCADE,
    admin_id bigint NOT NULL REFERENCES public.users(id) ON DELETE SET NULL,
    action text NOT NULL,
    previous_status text,
    new_status text,
    reason text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.rider_audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rider_id bigint NOT NULL REFERENCES public.riders(id) ON DELETE CASCADE,
    admin_id bigint NOT NULL REFERENCES public.users(id) ON DELETE SET NULL,
    action text NOT NULL,
    previous_status text,
    new_status text,
    reason text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_seller_audit_log_seller ON public.seller_audit_log(seller_id);
CREATE INDEX IF NOT EXISTS idx_seller_audit_log_admin ON public.seller_audit_log(admin_id);
CREATE INDEX IF NOT EXISTS idx_rider_audit_log_rider ON public.rider_audit_log(rider_id);
CREATE INDEX IF NOT EXISTS idx_rider_audit_log_admin ON public.rider_audit_log(admin_id);